language: java
jdk:
  - oraclejdk11
sudo: required
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
services: -docker
script:
  - docker-compose build
before_deploy:
  - docker login -u 127109 -p Mam/Dad/09
deploy:
  provider: script
  script: docker push services
  on:
    branch: master
