language: java
jdk:
  - oraclejdk11
sudo: required
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test
services: -docker
script:
  - docker-compose build -t 127109/first .

